# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: NODE_ENV=development npm install
  displayName: 'npm install'

- script: npx cross-env NODE_ENV=testing LOG_LEVEL=DEBUG nyc --reporter=cobertura -x \"config/*\" -x \"test/*\" mocha --recursive --exit --reporter mocha-junit-reporter
  displayName: 'run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'